# Generated by Django 4.1.6 on 2023-02-02 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='car',
            name='controlled_bridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.controlledbridge', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='driving_bridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.drivingbridge', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.engine', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='car',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='car',
            name='technic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.technic', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.transmission', verbose_name='Модель трансмиссии'),
        ),
    ]
